CRITICAL - 2022-02-25 02:22:57 --> Undefined index: Nom_Organisation_Contact
#0 C:\laragon\www\Luzancy-App\app\Views\Recherche\Contact\ListeContact.php(117): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\laragon\\www\\...', 117, Array)
#1 C:\laragon\www\Luzancy-App\system\View\View.php(210): include('C:\\laragon\\www\\...')
#2 C:\laragon\www\Luzancy-App\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\laragon\www\Luzancy-App\system\Common.php(1089): CodeIgniter\View\View->render('Recherche/Conta...', Array, true)
#4 C:\laragon\www\Luzancy-App\app\Controllers\Recherche.php(43): view('Recherche/Conta...', Array)
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Recherche->tout_les_contacts()
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Recherche))
#7 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-02-25 02:31:32 --> Undefined index: ID_Login
#0 C:\laragon\www\Luzancy-App\app\Views\Recherche\Login\ListeLogin.php(38): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined index...', 'C:\\laragon\\www\\...', 38, Array)
#1 C:\laragon\www\Luzancy-App\system\View\View.php(210): include('C:\\laragon\\www\\...')
#2 C:\laragon\www\Luzancy-App\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\laragon\www\Luzancy-App\system\Common.php(1089): CodeIgniter\View\View->render('Recherche/Login...', Array, true)
#4 C:\laragon\www\Luzancy-App\app\Controllers\Recherche.php(128): view('Recherche/Login...', Array)
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Recherche->tout_les_login()
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Recherche))
#7 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-02-25 03:00:22 --> Undefined variable: organisations
#0 C:\laragon\www\Luzancy-App\app\Views\Ajout\Contact\formulaire.php(48): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\laragon\\www\\...', 48, Array)
#1 C:\laragon\www\Luzancy-App\system\View\View.php(210): include('C:\\laragon\\www\\...')
#2 C:\laragon\www\Luzancy-App\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\laragon\www\Luzancy-App\system\Common.php(1089): CodeIgniter\View\View->render('Ajout/Contact/f...', Array, true)
#4 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(38): view('Ajout/Contact/f...')
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contacter()
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#7 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-02-25 03:36:40 --> There is no data to insert.
#0 C:\laragon\www\Luzancy-App\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\laragon\www\Luzancy-App\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(Array, 'insert')
#2 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(43): CodeIgniter\Model->insert(Array)
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-25 03:38:58 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
CRITICAL - 2022-02-25 03:38:58 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(43): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 03:40:22 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
CRITICAL - 2022-02-25 03:40:22 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(43): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 05:24:12 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `ID_organisation_contact` FOREIGN KEY (`ID_Organisation`) REFERENCES `organisation` (`ID_Organisation`))
CRITICAL - 2022-02-25 05:24:12 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `ID_organisation_contact` FOREIGN KEY (`ID_Organisation`) REFERENCES `organisation` (`ID_Organisation`))
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(43): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 05:25:31 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `ID_organisation_contact` FOREIGN KEY (`ID_Organisation`) REFERENCES `organisation` (`ID_Organisation`))
CRITICAL - 2022-02-25 05:25:31 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `ID_organisation_contact` FOREIGN KEY (`ID_Organisation`) REFERENCES `organisation` (`ID_Organisation`))
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(43): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-02-25 05:26:48 --> There is no data to insert.
#0 C:\laragon\www\Luzancy-App\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\laragon\www\Luzancy-App\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(Array, 'insert')
#2 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(43): CodeIgniter\Model->insert(Array)
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-25 06:09:10 --> syntax error, unexpected end of file, expecting elseif (T_ELSEIF) or else (T_ELSE) or endif (T_ENDIF)
#0 C:\laragon\www\Luzancy-App\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#1 C:\laragon\www\Luzancy-App\system\Common.php(1089): CodeIgniter\View\View->render('Ajout/Contact/f...', Array, true)
#2 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(44): view('Ajout/Contact/f...')
#3 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#6 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#7 {main}
CRITICAL - 2022-02-25 06:14:05 --> There is no data to insert.
#0 C:\laragon\www\Luzancy-App\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\laragon\www\Luzancy-App\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(Array, 'insert')
#2 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(43): CodeIgniter\Model->insert(Array)
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-25 06:29:27 --> Undefined variable: organisations
#0 C:\laragon\www\Luzancy-App\app\Views\Ajout\Contact\formulaire.php(52): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\laragon\\www\\...', 52, Array)
#1 C:\laragon\www\Luzancy-App\system\View\View.php(210): include('C:\\laragon\\www\\...')
#2 C:\laragon\www\Luzancy-App\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\laragon\www\Luzancy-App\system\Common.php(1089): CodeIgniter\View\View->render('Ajout/Contact/f...', Array, true)
#4 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(38): view('Ajout/Contact/f...')
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contacter()
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#7 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-02-25 07:24:58 --> There is no data to insert.
#0 C:\laragon\www\Luzancy-App\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\laragon\www\Luzancy-App\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(Array, 'insert')
#2 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-25 07:25:04 --> Undefined variable: valeur
#0 C:\laragon\www\Luzancy-App\app\Views\Ajout\Contact\formulaire.php(60): CodeIgniter\Debug\Exceptions->errorHandler(8, 'Undefined varia...', 'C:\\laragon\\www\\...', 60, Array)
#1 C:\laragon\www\Luzancy-App\system\View\View.php(210): include('C:\\laragon\\www\\...')
#2 C:\laragon\www\Luzancy-App\system\View\View.php(213): CodeIgniter\View\View->CodeIgniter\View\{closure}()
#3 C:\laragon\www\Luzancy-App\system\Common.php(1089): CodeIgniter\View\View->render('Ajout/Contact/f...', Array, true)
#4 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(42): view('Ajout/Contact/f...', Array)
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contacter()
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#7 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#9 {main}
CRITICAL - 2022-02-25 07:36:56 --> There is no data to insert.
#0 C:\laragon\www\Luzancy-App\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\laragon\www\Luzancy-App\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(Array, 'insert')
#2 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
CRITICAL - 2022-02-25 07:59:46 --> There is no data to insert.
#0 C:\laragon\www\Luzancy-App\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\laragon\www\Luzancy-App\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(Array, 'insert')
#2 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
ERROR - 2022-02-25 08:15:37 --> Duplicate entry '0' for key 'PRIMARY'
CRITICAL - 2022-02-25 08:15:37 --> Duplicate entry '0' for key 'PRIMARY'
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 08:16:41 --> Duplicate entry '0' for key 'PRIMARY'
CRITICAL - 2022-02-25 08:16:41 --> Duplicate entry '0' for key 'PRIMARY'
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 08:16:56 --> Duplicate entry '0' for key 'PRIMARY'
CRITICAL - 2022-02-25 08:16:56 --> Duplicate entry '0' for key 'PRIMARY'
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 08:19:10 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
CRITICAL - 2022-02-25 08:19:10 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 08:20:55 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
CRITICAL - 2022-02-25 08:20:55 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
ERROR - 2022-02-25 08:21:13 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
CRITICAL - 2022-02-25 08:21:13 --> Cannot add or update a child row: a foreign key constraint fails (`test`.`contact`, CONSTRAINT `Nom_Organisation_Contact` FOREIGN KEY (`Nom_Organisation_Contact`) REFERENCES `organisation` (`Nom_Organisation`))
#0 C:\laragon\www\Luzancy-App\system\Database\MySQLi\Connection.php(292): mysqli->query('INSERT INTO `co...', 0)
#1 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `co...')
#2 C:\laragon\www\Luzancy-App\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `co...')
#3 C:\laragon\www\Luzancy-App\system\Database\BaseBuilder.php(1771): CodeIgniter\Database\BaseConnection->query('INSERT INTO `co...', Array, false)
#4 C:\laragon\www\Luzancy-App\system\Model.php(239): CodeIgniter\Database\BaseBuilder->insert()
#5 C:\laragon\www\Luzancy-App\system\BaseModel.php(738): CodeIgniter\Model->doInsert(Array)
#6 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#7 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#8 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#9 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#10 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#12 {main}
CRITICAL - 2022-02-25 08:21:49 --> There is no data to insert.
#0 C:\laragon\www\Luzancy-App\system\BaseModel.php(1574): CodeIgniter\Database\Exceptions\DataException::forEmptyDataset('insert')
#1 C:\laragon\www\Luzancy-App\system\BaseModel.php(704): CodeIgniter\BaseModel->transformDataToArray(Array, 'insert')
#2 C:\laragon\www\Luzancy-App\system\Model.php(625): CodeIgniter\BaseModel->insert(Array, true)
#3 C:\laragon\www\Luzancy-App\app\Controllers\Ajouter.php(51): CodeIgniter\Model->insert(Array)
#4 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(825): App\Controllers\Ajouter->ajouter_contact_record()
#5 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(412): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Ajouter))
#6 C:\laragon\www\Luzancy-App\system\CodeIgniter.php(320): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#7 C:\laragon\www\Luzancy-App\public\index.php(37): CodeIgniter\CodeIgniter->run()
#8 {main}
